# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
 pipelines:
  - pipeline: buildContosoAir # identifier for the resource used in pipeline resource variables
    source: Student1-60878313.ContosoAir # name of the pipeline that produces the artifact
    trigger:
     branches:
      include:
       - master

pool:
  name: default

steps:
- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure Connection'
    appType: 'webApp'
    WebAppName: '$(web_prefix)-$(web_site)-$(web_environment)'
    packageForLinux: '$(Pipeline.Workspace)/**/*.zip'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
