trigger:
  - master

resources:
  pipelines:
    - pipeline: buildContosoAir
      source: Shayeghi.ContosoAir
      trigger:
        branches:
          include:
            - master

pool:
  name: default

steps:
  - task: DownloadPipelineArtifact@2
    displayName: 'Download build artifact'
    inputs:
      buildType: 'specific'
      project: '8bb23d26-b11e-4b1d-b801-144da5d737a6'
      definition: '3'
      buildVersionToDownload: 'latest'
      targetPath: '$(Pipeline.Workspace)'

  - script: |
      echo Listing files:
      dir "$(Pipeline.Workspace)\drop" /s
    displayName: 'List downloaded files'

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Deploy ARM Template'
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'Azure Connection'
      subscriptionId: '65991389-0380-497d-a132-2e57b19f198d'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'rg-lod'
      location: 'Canada Central'
      templateLocation: 'Linked artifact'
      csmFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.json'
      csmParametersFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.parameters.json'
      overrideParameters: '-p_environment $(web_environment) -p_site_prefix $(web_prefix) -p_site_web_name $(web_site)'
      deploymentMode: 'Incremental'

  - task: AzureRmWebAppDeployment@5
    displayName: 'Deploy Web App'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure Connection'
      appType: 'webApp'
      WebAppName: '$(web_prefix)-$(web_site)-$(web_environment)'
      packageForLinux: '$(Pipeline.Workspace)/drop/28.zip'

  - script: |
      echo Deployment completed.
    displayName: 'Final step'