# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.

trigger: none

resources:
  pipelines:
    - pipeline: buildContosoAir
      source: Student1-60878313.ContosoAir
      trigger:
        branches:
          include:
            - master

pool:
  name: default

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Deploy ARM Template'
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'Azure Connection'
      subscriptionId: '65991389-0380-497d-a132-2e57b19f198d'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'rg-lod'
      location: 'Canada Central'
      templateLocation: 'Linked artifact'
      csmFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.json'
      csmParametersFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.parameters.json'
      overrideParameters: '-p_environment $(web_environment) -p_site_prefix $(web_prefix) -p_site_web_name $(web_site)'
      deploymentMode: 'Incremental'

  - task: AzureRmWebAppDeployment@5
    displayName: 'Deploy Web App'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure Connection'
      appType: 'webApp'
      WebAppName: '$(web_prefix)-$(web_site)-$(web_environment)'
      packageForLinux: '$(Pipeline.Workspace)/**/*.zip'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'